Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/09/2020
Var
cont, numero: inteiro

Inicio
para cont de 1 ate 10 passo +1 faca
     escreval("Digite o valor do numero", cont)
     leia(numero)
     se(numero mod 2 = 0) entao
     escreval("O Numero é par")
     senao
     escreval("O Numero é Ímpar")
     fimse
fimpara


Fimalgoritmo