Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2020
Var
   a, b: inteiro


Inicio
   escreval("Digite um número:")
   leia(a)
   escreval("Digite outro número:")
   leia(b)
   escreval(a, " +",b," =", a+b)
   escreval(a, " -",b," =", a-b)
   escreval(a, " x",b," =", a*b)
   escreval(a, " /",b," =", a/b)

Fimalgoritmo